### ISSUE TITLE
Code Lab Feedback

### ISSUE THREAD

**Issue by ackleyd1** [ackleyd1/codelab-multipage-websites#1]
Hey @icy-wolf, can you take a look at this? It's [hosted here](http://mysterious-arm.surge.sh/Akers127/) and meets the following [project](http://lansingcodelab.com/lessons/multipage-websites/1) criteria:
- [x] a `/students` route exists, that lists the first names of 3 other Code Lab students (seek their permission first - if they're not comfortable with their first name on the page, you can make up a name)
- [x] a route for each student exists at `/students/NAME`, where their name and favorite color is featured

**Comment by ackleyd1** [comment]
Not the exact same suggested project but the same idea

**Comment by icy-wolf** [comment]
:shipit:
